from .user import UserViewset
from .sectores import SectoresViewSet
from .usuarios import UsuarioViewSet
from .proyectos import ProyectoViewSet
from .servicios import ServicioViewSet
from .detalle import DetalleViewSet
from .configuracion import ConfigViewSet
from .dashboard import DashboardViewSet
from .fallecidos import FallecidosViewSet
