# Generated by Django 2.2.9 on 2021-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sector_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dpi',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
