# Generated by Django 3.1.7 on 2021-06-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='costo',
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('tipo', models.IntegerField(choices=[(10, 'Servicio Agua'), (20, 'Servicio Cementerio')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='api.usuario')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
