# Generated by Django 2.2.9 on 2021-06-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210628_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('tipo', models.IntegerField(choices=[(10, 'Servicio Agua'), (20, 'Servicio Cementerio')])),
                ('tipo_detalle', models.IntegerField(choices=[(10, 'Ingreso'), (20, 'Egreso'), (30, 'Neutro')])),
                ('descripcion', models.TextField()),
                ('monto', models.FloatField()),
                ('cerrado', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.Proyecto')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
