# Generated by Django 2.2.9 on 2021-07-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_detalle'),
        ('api', '0006_pago'),
    ]

    operations = [
    ]
