# Generated by Django 2.2.9 on 2021-07-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20210703_2125'),
        ('api', '0007_merge_20210704_0206'),
    ]

    operations = [
    ]
