# Generated by Django 2.2.9 on 2021-07-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20210704_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='anio',
            field=models.SmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='mes',
            field=models.SmallIntegerField(),
            preserve_default=False,
        ),
    ]
