# Generated by Django 2.2.9 on 2021-07-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210706_0306'),
        ('api', '0009_auto_20210704_0348'),
    ]

    operations = [
    ]
