# Generated by Django 2.2.9 on 2021-08-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='tipo_detalle',
        ),
        migrations.AlterField(
            model_name='detalle',
            name='tipo',
            field=models.IntegerField(choices=[(10, 'Ingreso'), (20, 'Egreso'), (30, 'Neutro')]),
        ),
    ]
