# Generated by Django 2.2.9 on 2021-10-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_proyecto_cerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='no_predio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
